services:
  grpc-client:
    image: grpc-client:latest
    environment:
      APP_PORT: "8080"
      GRPC_SERVER_ADDRESS: "grpc-server:9090"
    ports:
      - "8080:8080"
    networks:
      - grpc-net
networks:
  grpc-net: