services:
  grpc-client:
    image: grpc-client:latest
    environment:
      SERVER: "server-1"
      GRPC_SERVER_ADDRESS: "host.docker.internal:9090"
    ports:
      - "8080:8080"
networks:
  grpc-net:
    driver: bridge